import { SHAPE_DATA as ALL_SHAPE_DATA } from './shapeData';
import type { SurfaceAreaTrainingStep, ShapeType } from '../../../types';

// Re-export shape data for convenience
export const SHAPE_DATA = ALL_SHAPE_DATA;

export const CUBE_TRAINING_PLAN: SurfaceAreaTrainingStep[] = [
    {
        step: 0,
        type: 'intro',
        title: 'Meet the Cube!',
        text: "This is a cube. All its sides are equal squares. Let's learn how to measure it.",
        duration: 5000,
    },
    {
        step: 1,
        type: 'action',
        title: "Adjust the Side Length",
        text: "The only dimension we need for a cube is the length of its side, which we call 'a'. Try changing its value using the slider.",
        requiredAction: 'change_dimension',
        spotlightOn: 'dimension-side',
    },
    {
        step: 2,
        type: 'action',
        title: 'Great!',
        text: "You can make the cube bigger or smaller. Press Continue when you are ready to calculate volume.",
        requiredAction: 'continue',
        spotlightOn: 'continue-button',
    },
    {
        step: 3,
        type: 'action',
        title: 'Calculate Volume',
        text: "Volume is the space inside the cube. Select 'Volume' from the calculation type dropdown.",
        requiredAction: 'select_calc_type',
        requiredValue: 'volume',
        spotlightOn: 'calc-type-selector',
    },
    {
        step: 4,
        type: 'action',
        title: 'Get the Answer',
        text: "The formula for a cube's volume is V = a³. Now, press the 'Calculate' button to see the result.",
        requiredAction: 'calculate',
        requiredValue: 'volume',
        spotlightOn: 'calculate-button',
    },
    {
        step: 5,
        type: 'action',
        title: "Intro to Surface Area",
        text: "Excellent! Now let's look at Surface Area. First up is Lateral Surface Area, or LSA. Press Continue.",
        requiredAction: 'continue',
        spotlightOn: 'continue-button',
    },
    {
        step: 6,
        type: 'action',
        title: 'Select LSA',
        text: "LSA is the area of just the side faces, not the top or bottom. Select 'LSA' from the dropdown.",
        requiredAction: 'select_calc_type',
        requiredValue: 'lsa',
        spotlightOn: 'calc-type-selector',
    },
    {
        step: 7,
        type: 'feedback',
        title: 'Visualizing LSA',
        text: "To see this clearly, let's unfold the cube. LSA is the area of these 4 side faces. The formula is 4 × a².",
        duration: 7000,
        highlightPartId: ['front', 'back', 'left', 'right'],
        unfoldOnStep: true,
    },
    {
        step: 8,
        type: 'action',
        title: 'Calculate LSA',
        text: "Now, press 'Calculate' to find the Lateral Surface Area.",
        requiredAction: 'calculate',
        requiredValue: 'lsa',
        spotlightOn: 'calculate-button',
    },
    {
        step: 9,
        type: 'action',
        title: "From LSA to TSA",
        text: "Great! Total Surface Area (TSA) is easy now. We just add the areas of the top and bottom faces to the LSA. Press Continue.",
        requiredAction: 'continue',
        spotlightOn: 'continue-button',
    },
    {
        step: 10,
        type: 'action',
        title: 'Area of One Face',
        text: "The area of one of these square faces is side × side, or a². Watch one face highlight, then press Continue.",
        duration: 6000,
        highlightPartId: 'front',
        requiredAction: 'continue',
        spotlightOn: 'continue-button',
    },
     {
        step: 11,
        type: 'action',
        title: 'Calculate Total Surface Area',
        text: "Since there are 6 identical faces in total, the formula is 6 × a². Select 'Total Surface Area' (TSA).",
        requiredAction: 'select_calc_type',
        requiredValue: 'tsa',
        spotlightOn: 'calc-type-selector',
        highlightPartId: ['front', 'back', 'top', 'bottom', 'left', 'right'],
    },
    {
        step: 12,
        type: 'action',
        title: 'Get the Answer',
        text: "Now, press 'Calculate' to find the Total Surface Area.",
        requiredAction: 'calculate',
        requiredValue: 'tsa',
        spotlightOn: 'calculate-button',
    },
    {
        step: 13,
        type: 'action',
        title: "Fold it back!",
        text: "You've mastered the cube's net! Press the 'Fold' button to turn it back into a 3D shape.",
        requiredAction: 'unfold',
        spotlightOn: 'unfold-button'
    },
    {
        step: 14,
        type: 'complete',
        title: 'Training Complete!',
        text: "Fantastic work! You've learned about the cube. You can now explore other shapes or try the challenges.",
    },
];

export const CUBOID_TRAINING_PLAN: SurfaceAreaTrainingStep[] = [
    { step: 0, type: 'intro', title: 'Meet the Cuboid!', text: "This is a cuboid. It's like a stretched-out cube, with rectangular faces. Let's explore it.", duration: 6000 },
    { step: 1, type: 'action', title: "Adjust the Dimensions", text: "A cuboid has three key dimensions: length (l), width (w), and height (h). Try changing them with the sliders.", requiredAction: 'change_dimension', spotlightOn: 'dimension-length' },
    { step: 2, type: 'action', title: 'Great!', text: "You can change the cuboid's shape. Press Continue when you are ready to calculate volume.", requiredAction: 'continue', spotlightOn: 'continue-button' },
    { step: 3, type: 'action', title: 'Calculate Volume', text: "The volume formula is V = l × w × h. Ensure 'Volume' is selected, then press 'Calculate'.", requiredAction: 'calculate', requiredValue: 'volume', spotlightOn: 'calculate-button' },
    { step: 4, type: 'action', title: "Intro to Surface Area", text: "Excellent! Now for Surface Area. Press Continue to start.", requiredAction: 'continue', spotlightOn: 'continue-button' },
    { step: 5, type: 'action', title: 'Unfold for LSA', text: "LSA is the area of the 4 side faces, excluding the top and bottom. Unfold the cuboid to see this clearly.", requiredAction: 'unfold', spotlightOn: 'unfold-button' },
    { step: 6, type: 'feedback', title: 'Visualizing LSA', text: "See? The LSA is the area of these four highlighted rectangles. The formula is 2(l+w)h.", duration: 8000, highlightPartId: ['front', 'back', 'left', 'right'] },
    { step: 7, type: 'action', title: 'Select LSA', text: "Now, select 'LSA' from the dropdown to prepare for calculation.", requiredAction: 'select_calc_type', requiredValue: 'lsa', spotlightOn: 'calc-type-selector' },
    { step: 8, type: 'action', title: 'Calculate LSA', text: "Great! Press 'Calculate' to see the result.", requiredAction: 'calculate', requiredValue: 'lsa', spotlightOn: 'calculate-button' },
    { step: 9, type: 'feedback', title: "Total Surface Area (TSA)", text: "Perfect! TSA is just the LSA plus the area of the top and bottom faces. All 6 faces are now highlighted.", duration: 8000, highlightPartId: ['front', 'back', 'top', 'bottom', 'left', 'right'] },
    { step: 10, type: 'action', title: 'Select TSA', text: "The formula is 2(lw + lh + wh). Select 'TSA' from the dropdown.", requiredAction: 'select_calc_type', requiredValue: 'tsa', spotlightOn: 'calc-type-selector' },
    { step: 11, type: 'action', title: 'Calculate TSA', text: "Now, press 'Calculate' to find the Total Surface Area.", requiredAction: 'calculate', requiredValue: 'tsa', spotlightOn: 'calculate-button' },
    { step: 12, type: 'action', title: "Fold it back!", text: "You've mastered the cuboid! Press 'Fold' to make it a 3D shape again.", requiredAction: 'unfold', spotlightOn: 'unfold-button' },
    { step: 13, type: 'complete', title: 'Training Complete!', text: "Fantastic work! You've learned about the cuboid." },
];

export const CYLINDER_TRAINING_PLAN: SurfaceAreaTrainingStep[] = [
    { step: 0, type: 'intro', title: 'Meet the Cylinder!', text: "This is a cylinder. It has two circular bases and a curved side. Let's measure it.", duration: 6000 },
    { step: 1, type: 'action', title: "Adjust the Dimensions", text: "A cylinder is defined by its radius (r) and height (h). Try changing them with the sliders.", requiredAction: 'change_dimension', spotlightOn: 'dimension-radius' },
    { step: 2, type: 'action', title: 'Perfect!', text: "Notice how the shape changes. Press Continue to calculate its volume.", requiredAction: 'continue', spotlightOn: 'continue-button' },
    { step: 3, type: 'action', title: 'Calculate Volume', text: "The formula for volume is V = πr²h. Select 'Volume' and press 'Calculate'.", requiredAction: 'calculate', requiredValue: 'volume', spotlightOn: 'calculate-button' },
    { step: 4, type: 'action', title: "Unfold for Surface Area", text: "Now for Surface Area. Let's unfold the cylinder to understand it better. Press 'Unfold'.", requiredAction: 'unfold', spotlightOn: 'unfold-button' },
    { step: 5, type: 'feedback', title: 'Visualizing LSA', text: "The curved side becomes a rectangle! Its width is the circle's circumference (2πr) and its height is the cylinder's height (h).", duration: 9000, highlightPartId: 'body' },
    { step: 6, type: 'action', title: 'Select LSA', text: "The LSA is the area of this rectangle (2πrh). Select 'LSA' from the dropdown.", requiredAction: 'select_calc_type', requiredValue: 'lsa', spotlightOn: 'calc-type-selector' },
    { step: 7, type: 'action', title: 'Calculate LSA', text: "Now, press 'Calculate'.", requiredAction: 'calculate', requiredValue: 'lsa', spotlightOn: 'calculate-button' },
    { step: 8, type: 'feedback', title: "Total Surface Area (TSA)", text: "TSA includes the top and bottom circles. So, it's the LSA plus the area of two circles (2πr²).", duration: 8000, highlightPartId: ['body', 'caps'] },
    { step: 9, type: 'action', title: 'Select TSA', text: "The full formula is 2πr(r+h). Select 'TSA' now.", requiredAction: 'select_calc_type', requiredValue: 'tsa', spotlightOn: 'calc-type-selector' },
    { step: 10, type: 'action', title: 'Calculate TSA', text: "And press 'Calculate' to see the final area.", requiredAction: 'calculate', requiredValue: 'tsa', spotlightOn: 'calculate-button' },
    { step: 11, type: 'action', title: "Fold it back!", text: "Great job! Fold the shape back to see the cylinder again.", requiredAction: 'unfold', spotlightOn: 'unfold-button' },
    { step: 12, type: 'complete', title: 'Training Complete!', text: "You've mastered the cylinder! Well done." },
];

export const CONE_TRAINING_PLAN: SurfaceAreaTrainingStep[] = [
    { step: 0, type: 'intro', title: 'Meet the Cone!', text: "This is a cone, like a party hat! It has a circular base and a curved surface that comes to a point.", duration: 6000 },
    { step: 1, type: 'action', title: "Adjust the Dimensions", text: "A cone is defined by its radius (r) and its vertical height (h). Try changing them.", requiredAction: 'change_dimension', spotlightOn: 'dimension-radius' },
    { step: 2, type: 'action', title: 'Excellent!', text: "The cone changes shape. Press Continue to calculate the volume.", requiredAction: 'continue', spotlightOn: 'continue-button' },
    { step: 3, type: 'action', title: 'Calculate Volume', text: "A cone's volume is (1/3)πr²h. Select 'Volume' and calculate.", requiredAction: 'calculate', requiredValue: 'volume', spotlightOn: 'calculate-button' },
    { step: 4, type: 'action', title: "Unfold for Surface Area", text: "To understand surface area, we need to unfold the cone. Press 'Unfold'.", requiredAction: 'unfold', spotlightOn: 'unfold-button' },
    { step: 5, type: 'feedback', title: 'Slant Height (l)', text: "The curved surface becomes a sector. Its radius is the 'slant height' (l) of the cone, calculated using Pythagoras: l = √(r² + h²).", duration: 10000, highlightPartId: 'body' },
    { step: 6, type: 'action', title: 'Select LSA', text: "The LSA is the area of this curved surface (πrl). Select 'LSA' from the dropdown.", requiredAction: 'select_calc_type', requiredValue: 'lsa', spotlightOn: 'calc-type-selector', highlightPartId: 'body' },
    { step: 7, type: 'action', title: 'Calculate LSA', text: "Now press 'Calculate'. It will find the slant height first.", requiredAction: 'calculate', requiredValue: 'lsa', spotlightOn: 'calculate-button' },
    { step: 8, type: 'feedback', title: "Total Surface Area (TSA)", text: "TSA is the LSA plus the area of the circular base (πr²).", duration: 8000, highlightPartId: ['body', 'cap'] },
    { step: 9, type: 'action', title: 'Select TSA', text: "The full formula is πr(r+l). Select 'TSA'.", requiredAction: 'select_calc_type', requiredValue: 'tsa', spotlightOn: 'calc-type-selector' },
    { step: 10, type: 'action', title: 'Calculate TSA', text: "Finally, press 'Calculate' for the total area.", requiredAction: 'calculate', requiredValue: 'tsa', spotlightOn: 'calculate-button' },
    { step: 11, type: 'action', title: "Fold it back!", text: "You did it! Fold the shape to see the cone again.", requiredAction: 'unfold', spotlightOn: 'unfold-button' },
    { step: 12, type: 'complete', title: 'Training Complete!', text: "You've mastered the cone! Great job." },
];

export const SPHERE_TRAINING_PLAN: SurfaceAreaTrainingStep[] = [
    { step: 0, type: 'intro', title: 'Meet the Sphere!', text: "This is a sphere, a perfectly round 3D ball. It's defined by just one dimension.", duration: 6000 },
    { step: 1, type: 'action', title: "Adjust the Radius", text: "A sphere's size is determined by its radius (r). Change its value.", requiredAction: 'change_dimension', spotlightOn: 'dimension-radius' },
    { step: 2, type: 'action', title: 'Simple, right?', text: "Making it bigger or smaller is easy. Press Continue to calculate its volume.", requiredAction: 'continue', spotlightOn: 'continue-button' },
    { step: 3, type: 'action', title: 'Calculate Volume', text: "The formula is V = (4/3)πr³. Select 'Volume' and calculate.", requiredAction: 'calculate', requiredValue: 'volume', spotlightOn: 'calculate-button' },
    { step: 4, type: 'action', title: "Surface Area", text: "A sphere can't be unfolded, so it only has one total surface area. Press Continue.", requiredAction: 'continue', spotlightOn: 'continue-button' },
    { step: 5, type: 'action', title: 'Select Surface Area', text: "For a sphere, LSA and TSA are the same. The formula is 4πr². Select 'TSA'.", requiredAction: 'select_calc_type', requiredValue: 'tsa', spotlightOn: 'calc-type-selector', highlightPartId: 'body' },
    { step: 6, type: 'action', title: 'Calculate Surface Area', text: "Now, press 'Calculate'.", requiredAction: 'calculate', requiredValue: 'tsa', spotlightOn: 'calculate-button' },
    { step: 7, type: 'complete', title: 'Training Complete!', text: "Excellent! You have mastered the sphere." },
];

export const TRAINING_PLANS: Record<ShapeType, SurfaceAreaTrainingStep[]> = {
    cube: CUBE_TRAINING_PLAN,
    cuboid: CUBOID_TRAINING_PLAN,
    cylinder: CYLINDER_TRAINING_PLAN,
    cone: CONE_TRAINING_PLAN,
    sphere: SPHERE_TRAINING_PLAN,
    // Add placeholders for other shapes to avoid errors, even though they won't be selectable in training
    hemisphere: [],
    cone_on_hemisphere: [],
    cylinder_with_hemispheres: [],
    cone_on_cylinder: [],
    frustum: [],
};