import type { FractionTrainingStep } from '../../../types';

export const fractionTrainingPlan: FractionTrainingStep[] = [
  // --- Part 1: Equal Shares & Fractional Units ---
  {
    step: 0,
    type: 'intro',
    ui: 'concept',
    text: "Welcome to training! Let's learn the basics of fractions.",
    duration: 3500,
  },
  {
    step: 1,
    type: 'feedback',
    ui: 'concept',
    text: "A fraction means a whole is cut into EQUAL shares. The DENOMINATOR (bottom number) tells us how many.",
    duration: 5000,
  },
  {
    step: 2,
    type: 'action',
    ui: 'concept',
    text: "Let's cut the whole into 4 equal shares. Click 'Cut in 4'.",
    requiredAction: 'set_denominator',
    requiredValue: 4,
    spotlightOn: 'denominator-4',
  },
  {
    step: 3,
    type: 'feedback',
    ui: 'concept',
    text: "Great! Each piece is a 'fractional unit'. Here, each piece is one-fourth (1/4).",
    duration: 5000,
  },
  {
    step: 4,
    type: 'feedback',
    ui: 'concept',
    text: "The NUMERATOR (top number) counts how many pieces we have.",
    duration: 4000,
  },
  {
    step: 5,
    type: 'action',
    ui: 'concept',
    text: "Click on 3 pieces to make the fraction 3/4.",
    requiredAction: 'select_pieces',
    count: 3,
    spotlightOn: 'pieces',
  },
  {
    step: 6,
    type: 'feedback',
    ui: 'concept',
    text: "Excellent! You've made 3/4. You understand the parts of a fraction!",
    duration: 4000,
  },

  // --- Part 2: Number Line ---
  {
    step: 7,
    type: 'intro',
    ui: 'number_line',
    text: "Fractions are numbers. We can place them on a number line between 0 and 1.",
    duration: 4000,
    requiredValue: 4, // Sets denominator for the number line
  },
  {
    step: 8,
    type: 'action',
    ui: 'number_line',
    text: "This number line is marked in fourths. Can you find and click on 2/4?",
    requiredAction: 'select_point',
    requiredValue: { numerator: 2, denominator: 4 },
    spotlightOn: 'number_line_point-2/4',
  },
  {
    step: 9,
    type: 'feedback',
    ui: 'number_line',
    text: "Exactly! Let's try another one.",
    duration: 2000,
    requiredValue: 8, // Switches to eighths
  },
  {
    step: 10,
    type: 'action',
    ui: 'number_line',
    text: "Now the line is in eighths. Find and click on 5/8.",
    requiredAction: 'select_point',
    requiredValue: { numerator: 5, denominator: 8 },
    spotlightOn: 'number_line_point-5/8',
  },
  {
    step: 11,
    type: 'feedback',
    ui: 'number_line',
    text: "You're a pro! Now you see how fractions have their own spot on the number line.",
    duration: 4000,
  },

  // --- Part 3: Addition & Simplification (Lowest Terms) ---
  {
    step: 12,
    type: 'intro',
    ui: 'operations',
    text: "Now for addition! Let's solve 1/4 + 1/4.",
    duration: 3000,
    clearBoardAfter: true,
  },
  {
    step: 13,
    type: 'action',
    ui: 'operations',
    text: "First, build the equation. Click '1/4'.",
    requiredAction: 'select_term1',
    requiredValue: { numerator: 1, denominator: 4 },
    spotlightOn: { numerator: 1, denominator: 4 },
  },
  {
    step: 14,
    type: 'action',
    ui: 'operations',
    text: "Now, click the '+' button.",
    requiredAction: 'select_operator',
    requiredValue: '+',
    spotlightOn: '+',
  },
  {
    step: 15,
    type: 'action',
    ui: 'operations',
    text: "Click '1/4' again to complete the equation.",
    requiredAction: 'select_term2',
    requiredValue: { numerator: 1, denominator: 4 },
    spotlightOn: { numerator: 1, denominator: 4 },
  },
  {
    step: 16,
    type: 'action',
    ui: 'operations',
    text: "The pieces are the same size, so this is easy! Click 'Solve'.",
    requiredAction: 'solve',
    spotlightOn: 'solve',
  },
  {
    step: 17,
    type: 'feedback',
    ui: 'operations',
    text: "When we add, we get 2/4. But look...",
    duration: 4000,
  },
  {
    step: 18,
    type: 'feedback',
    ui: 'operations',
    text: "...2/4 is the same length as 1/2! This is called simplifying to the LOWEST TERMS.",
    duration: 5000,
  },
  {
    step: 19,
    type: 'feedback',
    ui: 'operations',
    text: "So, the simplest and best answer is 1/2.",
    duration: 4000,
  },
  {
    step: 20,
    type: 'action',
    ui: 'operations',
    text: "Excellent! Ready for a subtraction challenge?",
    requiredAction: 'continue',
    spotlightOn: 'continue_button',
  },
  
  // --- Part 4: Subtraction ---
  {
    step: 21,
    type: 'intro',
    ui: 'operations',
    text: "Great! Let's try 1/2 - 1/4.",
    duration: 3000,
    clearBoardAfter: true,
  },
  {
    step: 22,
    type: 'action',
    ui: 'operations',
    text: "Build the equation. First, click '1/2'.",
    requiredAction: 'select_term1',
    requiredValue: { numerator: 1, denominator: 2 },
    spotlightOn: { numerator: 1, denominator: 2 },
  },
  {
    step: 23,
    type: 'action',
    ui: 'operations',
    text: "Now, click the '-' button.",
    requiredAction: 'select_operator',
    requiredValue: '-',
    spotlightOn: '-',
  },
  {
    step: 24,
    type: 'action',
    ui: 'operations',
    text: "Finally, click '1/4'.",
    requiredAction: 'select_term2',
    requiredValue: { numerator: 1, denominator: 4 },
    spotlightOn: { numerator: 1, denominator: 4 },
  },
  {
    step: 25,
    type: 'action',
    ui: 'operations',
    text: "The pieces are different sizes! Click 'Solve' to see the magic.",
    requiredAction: 'solve',
    spotlightOn: 'solve',
  },
  {
    step: 26,
    type: 'feedback',
    ui: 'operations',
    text: "Look! We show you the math. We multiply 1/2 by 2/2 to make the pieces match.",
    duration: 6000,
  },
  {
    step: 27,
    type: 'feedback',
    ui: 'operations',
    text: "Now that we have 2/4, we can subtract. The answer is 1/4!",
    duration: 5000,
    clearBoardAfter: true,
  },

  // --- Completion ---
  {
    step: 28,
    type: 'complete',
    ui: 'operations',
    text: "Training Complete! You're now a fraction master.",
  },
];