import type { FractionTrainingStep } from '../../../types';

// This training plan is structured to follow the pedagogical approach of
// NCERT Class 6th Maths, Chapter 7: Fractions.
export const fractionTrainingPlan: FractionTrainingStep[] = [
  // --- Part 1: Anatomy of a Fraction (NCERT 7.1-7.3) ---
  {
    step: 0,
    type: 'intro',
    ui: 'concept',
    text: "Welcome to Fraction Foundations! Let's learn about fractions step-by-step.",
    duration: 3500,
  },
  {
    step: 1,
    type: 'feedback',
    ui: 'concept',
    text: "A fraction represents a part of a whole. The whole must be divided into EQUAL parts.",
    duration: 5000,
  },
  {
    step: 2,
    type: 'feedback',
    ui: 'concept',
    text: "The DENOMINATOR (bottom number) tells us how many equal parts the whole is divided into.",
    duration: 5000,
  },
  {
    step: 3,
    type: 'action',
    ui: 'concept',
    text: "Let's divide the whole into 4 equal parts. Click 'Cut in 4'.",
    requiredAction: 'set_denominator',
    requiredValue: 4,
    spotlightOn: 'denominator-4',
  },
  {
    step: 4,
    type: 'feedback',
    ui: 'concept',
    text: "The NUMERATOR (top number) tells us how many of these parts we are considering.",
    duration: 5000,
  },
  {
    step: 5,
    type: 'action',
    ui: 'concept',
    text: "Click on 3 parts to represent the fraction three-fourths (3/4).",
    requiredAction: 'select_pieces',
    count: 3,
    spotlightOn: 'pieces',
  },
  {
    step: 6,
    type: 'feedback',
    ui: 'concept',
    text: "Excellent! You understand what numerators and denominators mean.",
    duration: 4000,
  },

  // --- Part 2: Fractions on the Number Line (NCERT 7.4) ---
  {
    step: 7,
    type: 'intro',
    ui: 'number_line',
    text: "Fractions are also numbers that can be shown on a number line.",
    duration: 4000,
    requiredValue: 4, // Sets denominator for the number line to fourths
  },
  {
    step: 8,
    type: 'action',
    ui: 'number_line',
    text: "This number line is divided into fourths. Can you find and click on 2/4?",
    requiredAction: 'select_point',
    requiredValue: { numerator: 2, denominator: 4 },
    spotlightOn: 'number_line_point-2/4',
  },
  {
    step: 9,
    type: 'feedback',
    ui: 'number_line',
    text: "Perfect! Let's switch to eighths.",
    duration: 2000,
    requiredValue: 8, // Switches to eighths
  },
  {
    step: 10,
    type: 'action',
    ui: 'number_line',
    text: "Now find and click on 5/8 on the number line.",
    requiredAction: 'select_point',
    requiredValue: { numerator: 5, denominator: 8 },
    spotlightOn: 'number_line_point-5/8',
  },
  {
    step: 11,
    type: 'feedback',
    ui: 'number_line',
    text: "Great job! You can pinpoint fractions on a number line.",
    duration: 4000,
  },

  // --- Part 3: Equivalent Fractions & Simplest Form (NCERT 7.5, 7.6) ---
  {
    step: 12,
    type: 'intro',
    ui: 'operations',
    text: "Now, let's add fractions with the same denominator, like 1/4 + 1/4.",
    duration: 4000,
    clearBoardAfter: true,
  },
  {
    step: 13,
    type: 'action',
    ui: 'operations',
    text: "First, click '1/4' on the wall.",
    requiredAction: 'select_term1',
    requiredValue: { numerator: 1, denominator: 4 },
    spotlightOn: { numerator: 1, denominator: 4 },
  },
  {
    step: 14,
    type: 'action',
    ui: 'operations',
    text: "Next, click the '+' button.",
    requiredAction: 'select_operator',
    requiredValue: '+',
    spotlightOn: '+',
  },
  {
    step: 15,
    type: 'action',
    ui: 'operations',
    text: "Click '1/4' again to complete the equation.",
    requiredAction: 'select_term2',
    requiredValue: { numerator: 1, denominator: 4 },
    spotlightOn: { numerator: 1, denominator: 4 },
  },
  {
    step: 16,
    type: 'action',
    ui: 'operations',
    text: "Since the pieces are the same size, we can add them. Click 'Solve'.",
    requiredAction: 'solve',
    spotlightOn: 'solve',
  },
  {
    step: 17,
    type: 'feedback',
    ui: 'operations',
    text: "The answer is 2/4. But notice that the 2/4 bar is the same length as the 1/2 bar!",
    duration: 6000,
  },
  {
    step: 18,
    type: 'feedback',
    ui: 'operations',
    text: "2/4 and 1/2 are called Equivalent Fractions. We always show the answer in its simplest form.",
    duration: 6000,
  },

  // --- Part 4: Adding & Subtracting Unlike Fractions (NCERT 7.7, 7.8) ---
  {
    step: 19,
    type: 'action',
    ui: 'operations',
    text: "Ready for the next concept?",
    requiredAction: 'continue',
    spotlightOn: 'continue_button',
  },
  {
    step: 20,
    type: 'intro',
    ui: 'operations',
    text: "What about fractions with different denominators, like 1/2 + 1/4?",
    duration: 4000,
    clearBoardAfter: true,
  },
  {
    step: 21,
    type: 'action',
    ui: 'operations',
    text: "Build the equation. Click '1/2'.",
    requiredAction: 'select_term1',
    requiredValue: { numerator: 1, denominator: 2 },
    spotlightOn: { numerator: 1, denominator: 2 },
  },
  {
    step: 22,
    type: 'action',
    ui: 'operations',
    text: "Click the '+' button.",
    requiredAction: 'select_operator',
    requiredValue: '+',
    spotlightOn: '+',
  },
  {
    step: 23,
    type: 'action',
    ui: 'operations',
    text: "And now click '1/4'.",
    requiredAction: 'select_term2',
    requiredValue: { numerator: 1, denominator: 4 },
    spotlightOn: { numerator: 1, denominator: 4 },
  },
  {
    step: 24,
    type: 'action',
    ui: 'operations',
    text: "We can't add pieces of different sizes. Click 'Solve' to see how we fix this.",
    requiredAction: 'solve',
    spotlightOn: 'solve',
  },
  {
    step: 25,
    type: 'feedback',
    ui: 'operations',
    text: "To make the pieces match, we find a Common Denominator. We turn 1/2 into 2/4.",
    duration: 6000,
  },
  {
    step: 26,
    type: 'feedback',
    ui: 'operations',
    text: "Now we can add 2/4 and 1/4 to get the answer: 3/4!",
    duration: 5000,
    clearBoardAfter: true,
  },

  // --- Completion ---
  {
    step: 27,
    type: 'complete',
    ui: 'operations',
    text: "Training Complete! You're ready to solve any problem.",
  },
];
